<?php
/**
 * Created by PhpStorm.
 * User: nvk3d
 * Date: 10.05.17
 * Time: 21:55
 */

namespace app\modules\common\controllers;


use app\models\Common;
use yii\rest\Controller;
use Yii;

class RestController extends Controller
{
    public function beforeAction($action)
    {
        if (Yii::$app->user->isGuest) {
            Common::setStatusCode(403);
        }
        return parent::beforeAction($action); // TODO: Change the autogenerated stub
    }
}